#!/usr/bin/env bash
# =============================================================================
# Provisions the PostgreSQL database, its three roles and their generated
# passwords, then applies every migration in order.
#
#   ./scripts/setup-db.sh            # create if missing, apply migrations
#   ./scripts/setup-db.sh --reset    # drop and recreate from scratch
#
# Roles
#   app_owner   owns the schema. Used by migrations and seeding only, never by
#               the running application. Holds BYPASSRLS so it can bootstrap
#               the very first administrator.
#   app_client  the application's business-data role. RLS is FORCED on it.
#   app_auth    credentials + session store only; no access to report data.
#
# Credentials land in .env.local (git-ignored) and are reused on re-runs.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"
DB_NAME="${DB_NAME:-rental_commissions}"
DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-5432}"

as_super() { su postgres -c "psql -v ON_ERROR_STOP=1 -qtAX $*"; }

gen_pw() { head -c 32 /dev/urandom | base64 | tr -d '/+=\n' | cut -c1-24; }
read_env() { grep -E "^$1=" "$ENV_FILE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"'; }

if [ -f "$ENV_FILE" ]; then
  OWNER_PW="$(read_env APP_OWNER_PASSWORD)"
  CLIENT_PW="$(read_env APP_CLIENT_PASSWORD)"
  AUTH_PW="$(read_env APP_AUTH_PASSWORD)"
  SESSION_SECRET="$(read_env SESSION_SECRET)"
fi
OWNER_PW="${OWNER_PW:-$(gen_pw)}"
CLIENT_PW="${CLIENT_PW:-$(gen_pw)}"
AUTH_PW="${AUTH_PW:-$(gen_pw)}"
SESSION_SECRET="${SESSION_SECRET:-$(head -c 48 /dev/urandom | base64 | tr -d '\n')}"

# -------------------------------------------------------------------- roles
echo "==> ensuring roles"
as_super "-c \"do \\\$\\\$ begin
  if not exists (select 1 from pg_roles where rolname='app_owner')  then create role app_owner  login; end if;
  if not exists (select 1 from pg_roles where rolname='app_client') then create role app_client login; end if;
  if not exists (select 1 from pg_roles where rolname='app_auth')   then create role app_auth   login; end if;
end \\\$\\\$;\""
as_super "-c \"alter role app_owner  with password '$OWNER_PW'  bypassrls nosuperuser createdb\""
as_super "-c \"alter role app_client with password '$CLIENT_PW' nobypassrls nosuperuser nocreatedb nocreaterole\""
as_super "-c \"alter role app_auth   with password '$AUTH_PW'   nobypassrls nosuperuser nocreatedb nocreaterole\""

# Operator resolution: managed providers install extensions into their own
# schema, so both application roles must be able to see it. Harmless locally —
# a schema that does not exist is skipped during resolution. Kept next to role
# creation because altering a role needs rights the migration role lacks.
as_super "-c \"alter role app_client set search_path = public, app, extensions\""
as_super "-c \"alter role app_auth   set search_path = public, app, extensions\""

# ----------------------------------------------------------------- database
if [ "${1:-}" = "--reset" ]; then
  echo "==> dropping database $DB_NAME"
  as_super "-c \"drop database if exists $DB_NAME with (force)\""
fi

if [ "$(as_super "-c \"select 1 from pg_database where datname='$DB_NAME'\"")" != "1" ]; then
  echo "==> creating database $DB_NAME"
  as_super "-c \"create database $DB_NAME owner app_owner\""
fi

# pgcrypto and citext are trusted extensions, but the schema must belong to the
# owner role before it can install them.
as_super "-d $DB_NAME -c \"alter schema public owner to app_owner\""

# --------------------------------------------------------------- migrations
OWNER_URL="postgres://app_owner:$OWNER_PW@$DB_HOST:$DB_PORT/$DB_NAME"
for file in "$ROOT"/db/migrations/*.sql; do
  echo "==> applying $(basename "$file")"
  PGPASSWORD="$OWNER_PW" psql -v ON_ERROR_STOP=1 -q "$OWNER_URL" -f "$file" 2>&1 | grep -v '^NOTICE' || true
done

# --------------------------------------------------------------- env.local
echo "==> writing $ENV_FILE"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-db.sh — do not commit.
APP_OWNER_PASSWORD=$OWNER_PW
APP_CLIENT_PASSWORD=$CLIENT_PW
APP_AUTH_PASSWORD=$AUTH_PW

# Business-data connection used by the app. RLS is FORCED for this role.
DATABASE_URL=postgres://app_client:$CLIENT_PW@$DB_HOST:$DB_PORT/$DB_NAME

# Credentials + session store only. No access to report data.
AUTH_DATABASE_URL=postgres://app_auth:$AUTH_PW@$DB_HOST:$DB_PORT/$DB_NAME

# Migrations and seeding only — never imported by application code.
OWNER_DATABASE_URL=$OWNER_URL

SESSION_SECRET=$SESSION_SECRET
EOF
chmod 600 "$ENV_FILE"

echo "==> database ready"
